### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by eder** [jlopezxs/express-inline-css#5]
Hello there,  I have this problem when try  using your lib...

Error: Cannot find module './lib/index'
Do you have some idea?
resolved in #6

**Comment by jlopezxs** [comment]
@eder Hello!
Yes, I fix this error in the build few minutes ago. Try again :+1: .
Thanks for report.

**Comment by selfagency** [comment]
i just got this same error on a fresh install from npm

**Comment by selfagency** [comment]
resolved in #6
